version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11
    steps:
      - checkout
      - run: echo "Hollow world!"

      - run:
          name: Install Newman
          command: 'sudo npm install -g newman'

      - run:
          name: API testing
          command: 'newman run ./.postman/CEM_Delete_User_API.postman_collection.json -e ./.postman/Test.template.postman_environment.json'
          #command: 'newman run ./postman/Test.postman_collection.json'
          #command: 'newman run https://www.getpostman.com/collections/c375c028eb7a29d6fe0e'